const $ = (selector) => document.querySelector(selector);
const icons = {
  home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-6h6v6"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  orders:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 3.5h6M8 9h8M8 13h8"/>',
  file:'<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h4"/>',
  message:'<path d="M4 5h16v12H9l-5 4z"/>',
  book:'<path d="M4 4h8v16H4zM12 4h8v16h-8z"/>',
  clinic:'<path d="M4 21V7l8-4 8 4v14zM9 21v-6h6v6M9 10h6M12 7v6"/>',
  bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
  chevron:'<path d="m9 18 6-6-6-6"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',
  upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5"/>',
  heart:'<path d="M20.8 8.5c0 5-8.8 11.3-8.8 11.3S3.2 13.5 3.2 8.5a4.8 4.8 0 0 1 8.8-2.6 4.8 4.8 0 0 1 8.8 2.6z"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4.5 3-7 8-7s8 2.5 8 7"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  filter:'<path d="M3 5h18l-7 8v6l-4 2v-8z"/>',
  paperclip:'<path d="m20 11-8 8a5 5 0 0 1-7-7l9-9a3.5 3.5 0 0 1 5 5l-9 9a2 2 0 0 1-3-3l8-8"/>',
  check:'<path d="m5 12 5 5L20 7"/>',
  back:'<path d="m15 18-6-6 6-6"/>',
  more:'<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>'
};
const icon = (name,size=18) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assets = '/assets/';
const orders = [
  {id:'CD-1042',patient:'Иванов А.В.',work:'Коронка E.max',date:'12.03.2024',status:'В работе',sum:'12 500 ₽',image:'tooth.png'},
  {id:'CD-1041',patient:'Петрова М.С.',work:'Мост (3 ед.)',date:'10.03.2024',status:'Согласование',sum:'8 900 ₽',image:'smile.png'},
  {id:'CD-1040',patient:'Смирнов К.О.',work:'Абатмент',date:'08.03.2024',status:'Новый',sum:'15 200 ₽',image:'tooth.png'},
  {id:'CD-1039',patient:'Кузнецова Е.А.',work:'Виниры (6 ед.)',date:'05.03.2024',status:'Завершен',sum:'18 700 ₽',image:'smile.png'},
  {id:'CD-1038',patient:'Лебедев Р.И.',work:'Временная конструкция',date:'04.03.2024',status:'В работе',sum:'9 300 ₽',image:'scan.png'},
  {id:'CD-1037',patient:'Соколов Д.В.',work:'Вкладка',date:'02.03.2024',status:'Завершен',sum:'11 600 ₽',image:'tooth.png'},
  {id:'CD-1036',patient:'Орлова Н.С.',work:'Коронка E.max',date:'28.02.2024',status:'В работе',sum:'14 200 ₽',image:'tooth.png'},
  {id:'CD-1035',patient:'Морозов К.А.',work:'Мост (4 ед.)',date:'25.02.2024',status:'На согласовании',sum:'22 800 ₽',image:'scan.png'}
];
const nav = [['home','Главная','home'],['new','Новый заказ','plus'],['orders','Мои заказы','orders'],['files','Файлы','file'],['messages','Сообщения','message'],['reference','Справочник','book'],['clinic','Моя клиника','clinic']];
const steps = ['Пациент','Конструкция','Зубы','Дополнительно','Подтверждение'];
const state = {page:'home',step:0,filter:'Все',query:'',orderId:'CD-1042',detailTab:'Обзор',fileTab:'Все файлы',clinicTab:'Основная информация',selectedTeeth:[16,26],dentition:'Постоянные зубы',work:'Коронка',messages:[{from:'them',text:'Добрый день! Можно уточнить срок по заказу CD-1041?',time:'10:04'},{from:'me',text:'Здравствуйте! Заказ находится на этапе согласования, ориентировочный срок готовности 10.03.2024.',time:'10:26'},{from:'them',text:'Спасибо!',time:'10:27'}],chatText:'',uploaded:[],form:{surname:'Иванов',initials:'А.В.',phone:'',birth:'',construction:'Коронка E.max',material:'Керамика E.max',quantity:'2',due:'2024-03-20',shade:'A2',comment:''},toast:''};
const statusClass = s => s==='В работе'?'green':s==='Завершен'?'green':s==='Новый'?'blue':'orange';
const badge = s => `<span class="badge ${statusClass(s)}">${s}</span>`;
const button = (label,action,kind='primary',extra='') => `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
function sidebar(){return `<aside class="sidebar" id="sidebar"><div class="brand" aria-label="Create Dental"><span>CRÉATE</span><small>DENTAL</small></div><nav class="sidebar-nav">${nav.map(([id,label,ico])=>`<button class="nav-link ${state.page===id||(state.page==='detail'&&id==='orders')?'active':''}" data-page="${id}">${icon(ico,17)}<span>${label}</span></button>`).join('')}</nav><div class="help-box">${icon('message',18)}<div><strong>Нужна помощь?</strong><span>Напишите нам</span></div></div></aside>`}
function header(){return `<header class="topbar"><button class="mobile-menu" data-action="menu" aria-label="Открыть меню">☰</button><div class="topbar-spacer"></div><span class="topbar-label">Клиника</span><select class="clinic-select" aria-label="Клиника"><option>Dental Clinic</option></select><button class="bell" aria-label="Уведомления" data-action="notifications">${icon('bell',19)}<i></i></button><button class="profile" data-page="clinic"><span class="avatar">ДИ</span><span><strong>Dr. Иванов</strong><small>Стоматологическая клиника</small></span>${icon('chevron',13)}</button></header>`}
function shell(content){$('#app').innerHTML=`${sidebar()}<div class="shell">${header()}<main class="content">${content}</main></div><div class="toast ${state.toast?'visible':''}">${escapeHtml(state.toast)}</div>`;}
function title(text,sub='',right=''){return `<div class="page-title"><div><h1>${text}</h1>${sub?`<p>${sub}</p>`:''}</div>${right}</div>`}
function tabs(items,selected,action='filter'){return `<div class="tabs">${items.map(([label,count])=>`<button class="tab ${selected===label?'active':''}" data-action="${action}" data-value="${label}">${label}${count!==undefined?` <span class="count">${count}</span>`:''}</button>`).join('')}</div>`}
function orderTable(list){return `<div class="table-wrap"><table class="orders-table"><thead><tr><th>№</th><th>Пациент</th><th>Тип работы</th><th>Срок</th><th>Статус</th><th>Сумма</th><th></th></tr></thead><tbody>${list.map(o=>`<tr data-order="${o.id}" tabindex="0"><td><div class="order-id"><img src="${assets+o.image}" alt="">${o.id}</div></td><td>${o.patient}</td><td>${o.work}</td><td>${o.date}</td><td>${badge(o.status)}</td><td><strong>${o.sum}</strong></td><td class="arrow">→</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Заказы не найдены</td></tr>'}</tbody></table></div>`}
function dashboard(){shell(`${title('Доброе утро, Dr. Иванов!','Создавайте заказы, отслеживайте статус и получайте готовые работы в срок.',button(`${icon('plus',16)} Создать новый заказ`,'new'))}<div class="stats">${[['orders','12','Активных заказов','blue'],['clock','3','На согласовании','orange'],['user','5','В работе','navy'],['heart','24','Завершено (месяц)','green']].map(([ico,n,l,c])=>`<div class="stat card"><span class="stat-icon ${c}">${icon(ico,25)}</span><div><strong>${n}</strong><span>${l}</span></div><button class="stat-x" aria-label="Информация">×</button></div>`).join('')}</div><section class="hero"><div><h2>Качество в каждой детали</h2><p>Современные технологии. Надежные сроки.<br>Индивидуальный подход.</p></div><img src="${assets}banner-teeth.png" alt="Керамические зубные конструкции"></section><div class="section-heading"><h2>Мои заказы</h2><button class="text-link" data-page="orders">Все заказы →</button></div>${tabs([['Все',24],['Новые',3],['В работе',5],['На согласовании',3],['Завершенные',13]],state.filter)}${orderTable(filteredOrders().slice(0,4))}`)}
function filteredOrders(){let list=orders;if(state.filter==='Новые')list=list.filter(o=>o.status==='Новый');else if(state.filter==='В работе')list=list.filter(o=>o.status==='В работе');else if(state.filter==='На согласовании')list=list.filter(o=>o.status.includes('согласован')||o.status==='Согласование');else if(state.filter==='Завершенные')list=list.filter(o=>o.status==='Завершен');if(state.query)list=list.filter(o=>Object.values(o).some(v=>String(v).toLowerCase().includes(state.query.toLowerCase())));return list}
function ordersPage(){shell(`${title('Мои заказы')}${tabs([['Все',24],['Новые',3],['В работе',5],['На согласовании',3],['Завершенные',13]],state.filter)}<div class="toolbar"><label class="search">${icon('search',17)}<input id="order-search" value="${escapeHtml(state.query)}" placeholder="Поиск по номеру заказа, пациенту или типу работы..."></label>${button(`${icon('filter',15)} Фильтры`,'filters','outline')}</div>${orderTable(filteredOrders())}<div class="pagination"><button aria-label="Назад">‹</button><button class="active">1</button><button>2</button><button>3</button><button>…</button><button aria-label="Вперед">›</button></div>`)}
function toothChart(interactive=true){const upper=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28],lower=[48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];let teeth=[];upper.forEach((n,i)=>{let theta=Math.PI+(i/15)*Math.PI;teeth.push({n,x:150+113*Math.cos(theta),y:145+105*Math.sin(theta)})});lower.forEach((n,i)=>{let theta=Math.PI-(i/15)*Math.PI;teeth.push({n,x:150+113*Math.cos(theta),y:166+105*Math.sin(theta)})});return `<div class="tooth-chart"><svg viewBox="0 0 300 310" role="img" aria-label="Схема зубов"><path d="M45 146 C38 15 262 15 255 146M45 168 C38 295 262 295 255 168" fill="none" stroke="#b8c3d2" stroke-width="1.3" stroke-dasharray="3 4"/>${teeth.map(({n,x,y})=>`<g class="tooth ${state.selectedTeeth.includes(n)?'selected':''}" ${interactive?`data-tooth="${n}"`:''} style="cursor:${interactive?'pointer':'default'}"><circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="12"/><text x="${x.toFixed(1)}" y="${(y+3).toFixed(1)}" text-anchor="middle">${n}</text></g>`).join('')}</svg></div>`}
function stepper(){return `<div class="stepper">${steps.map((s,i)=>`<button class="step ${state.step===i?'active':''} ${state.step>i?'done':''}" data-step="${i}"><b>${state.step>i?icon('check',13):i+1}</b>${s}</button>${i<4?'<span class="step-line">→</span>':''}`).join('')}</div>`}
function field(label,control){return `<label class="field"><span>${label}</span>${control}</label>`}
function textInput(value='',placeholder='',key=''){return `<input ${key?`data-field="${key}"`:''} value="${escapeHtml(value)}" placeholder="${escapeHtml(placeholder)}">`}
function selectInput(options,key=''){return `<select ${key?`data-field="${key}"`:''}>${options.map(o=>`<option ${state.form[key]===o?'selected':''}>${o}</option>`).join('')}</select>`}
function patientStep(){return `<h2>Данные пациента</h2><div class="form-grid">${field('Фамилия пациента',textInput(state.form.surname,'','surname'))}${field('Имя и отчество',textInput(state.form.initials,'','initials'))}${field('Номер телефона',textInput(state.form.phone,'+7 (___) ___-__-__','phone'))}${field('Дата рождения',`<input type="date" data-field="birth" value="${state.form.birth}">`)}</div><div class="info-note">Укажите данные пациента для идентификации заказа. Они будут видны только вашей клинике.</div>`}
function constructionStep(){return `<h2>Выберите конструкцию</h2><div class="form-grid">${field('Тип конструкции',selectInput(['Коронка E.max','Винир','Мост','Абатмент','Вкладка'],'construction'))}${field('Материал',selectInput(['Керамика E.max','Диоксид циркония','Металлокерамика'],'material'))}${field('Количество единиц', `<input type="number" min="1" data-field="quantity" value="${escapeHtml(state.form.quantity)}">`)}${field('Срок изготовления',`<input type="date" data-field="due" value="${state.form.due}">`)}</div><div class="info-note">После выбора конструкции отметьте нужные зубы на схеме.</div>`}
function teethStep(){return `<div class="teeth-layout"><div>${toothChart()}<div class="chart-legend"><span><i class="dot blue"></i> Выбрано</span><span><i class="dot gray"></i> Не выбрано</span></div></div><div class="teeth-options"><h2>Выберите зубы на схеме</h2><div class="segmented">${['Постоянные зубы','Молочные зубы'].map(t=>`<button class="${state.dentition===t?'selected':''}" data-action="dentition" data-value="${t}">${t}</button>`).join('')}</div><h3>Выбранные зубы: ${state.selectedTeeth.join(', ')||'—'}</h3><div class="selected-teeth">${state.selectedTeeth.map(n=>`<button data-tooth="${n}">${n} ×</button>`).join('')}<button class="clear" data-action="clear-teeth">Очистить</button></div><h3>Тип работы</h3><div class="work-options">${['Коронка','Винир','Вкладка','Мост','Имплант. коронка','Абатмент','Съемный протез','Временная конструкция','Другое'].map(w=>`<button class="${state.work===w?'selected':''}" data-action="work" data-value="${w}">${w}</button>`).join('')}</div></div></div>`}
function attachmentTiles(){return `<div class="attachment-grid">${[['xray.png','Рентгеновский снимок'],['tooth.png','Фото зуба'],['scan.png','3D модель'],...state.uploaded.map(n=>['file.png',n])].map(([src,name])=>`<div class="attachment"><img src="${assets+src}" alt="${escapeHtml(name)}"><button aria-label="Удалить файл" data-action="remove-file" data-value="${escapeHtml(name)}">×</button></div>`).join('')}<label class="attachment-add" title="Добавить файлы">${icon('plus',26)}<input type="file" id="upload-input" multiple hidden></label></div>`}
function extraStep(){return `<h2>Дополнительная информация</h2><div class="form-grid">${field('Желаемый срок готовности',`<input type="date" data-field="due" value="${state.form.due}">`)}${field('Цвет/оттенок (например, Vita)',selectInput(['A2','A1','A3','B1','B2'],'shade'))}</div><div class="form-grid extra-fields"><div>${field('Прикрепить файлы','<label class="upload-zone">'+icon('upload',26)+'<span>Перетащите файлы сюда<br>или нажмите для выбора</span><input type="file" id="upload-input" multiple hidden></label>')}<small class="hint">Поддерживаются файлы: JPG, PNG, PDF, STL, PLY (до 50 МБ)</small></div>${field('Комментарий к заказу',`<textarea rows="5" data-field="comment" placeholder="Напишите пожелания, особенности, дополнительные инструкции...">${escapeHtml(state.form.comment)}</textarea>`)}</div><h3>Примеры прикрепленных файлов</h3>${attachmentTiles()}`}
function confirmStep(){return `<h2>Проверьте данные заказа</h2><div class="confirmation"><div>${toothChart(false)}</div><div class="summary-list">${[['Пациент',`${state.form.surname} ${state.form.initials}`],['Выбранные зубы',state.selectedTeeth.join(', ')],['Тип работы',state.form.construction],['Желаемый срок',state.form.due.split('-').reverse().join('.')],['Цвет',state.form.shade],['Комментарий',state.form.comment||'—'],['Файлы',`${3+state.uploaded.length} файла`]].map(([k,v])=>`<div><span>${k}</span><strong>${escapeHtml(v)}</strong></div>`).join('')}${attachmentTiles()}</div></div>`}
function newOrder(){const body=[patientStep,constructionStep,teethStep,extraStep,confirmStep][state.step]();shell(`${title(state.step===3?'Новый заказ — дополнительные параметры':state.step===4?'Новый заказ — подтверждение':'Новый заказ')}${stepper()}<section class="wizard">${body}<div class="wizard-actions">${state.step>0?button('Назад','previous','outline'):''}${button(state.step===4?'Создать заказ':'Далее →','next')}</div></section>`)}
function detail(){const o=orders.find(o=>o.id===state.orderId)||orders[0];shell(`<button class="back-link" data-page="orders">← &nbsp; Назад к заказам</button><div class="detail-heading">${title(`Заказ ${o.id}`,badge(o.status)+' <span class="muted">Создан 01.03.2024</span>',button(`${icon('message',16)} Сообщение`,'open-messages','outline'))}<button class="more-btn" aria-label="Дополнительно" data-action="more">${icon('more',19)}</button></div>${tabs([['Обзор'],['Файлы'],['Комментарии'],['История']],state.detailTab,'detail-tab')}${state.detailTab==='Обзор'?`<div class="detail-grid"><section><h3>Общая информация</h3><div class="facts">${[['Пациент',o.patient],['Выбранные зубы','16, 26'],['Тип работы',o.work],['Желаемый срок',state.form.due.split('-').reverse().join('.')],['Цвет',state.form.shade],['Комментарий',state.form.comment||'—']].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div></section><section><h3>Выбранные зубы</h3>${toothChart(false)}</section><section><h3>Статус заказа</h3><div class="timeline">${[['Новый','01.03.2024 10:24'],['На согласовании','01.03.2024 14:30'],['В работе','03.03.2024 09:15'],['Готов к отправке',''],['Завершен','']].map((x,i)=>`<div class="${i<3?'complete':''}"><i></i><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></section></div><h3 class="attachments-title">Прикрепленные файлы</h3>${attachmentTiles()}`:state.detailTab==='Файлы'?`<h3>Файлы заказа</h3>${attachmentTiles()}`:state.detailTab==='Комментарии'?'<div class="info-note">Комментарии к заказу пока отсутствуют.</div>':'<div class="info-note">Заказ создан 01.03.2024 и находится в работе.</div>'}`)}
function filesPage(){const files=[['xray.png','КТ_верхняя.jpg','12.03.2024','КТ/Рентген'],['tooth.png','Фото_16.jpg','12.03.2024','Фото'],['scan.png','Скан_верхняя.stl','10.03.2024','3D модели'],['smile.png','Прикус.jpg','10.03.2024','Фото'],['tooth.png','Фото_26.jpg','06.03.2024','Фото'],['file.png','План_лечения.pdf','08.03.2024','Документы'],['scan.png','Скан_нижняя.stl','05.03.2024','3D модели'],['xray.png','КТ_панорама.jpg','05.03.2024','КТ/Рентген'],['smile.png','Фото_улыбка.jpg','04.03.2024','Фото'],['tooth.png','Другое.jpg','04.03.2024','Фото']];shell(`${title('Файлы','',button(`${icon('plus',16)} Загрузить файл`,'upload'))}${tabs([['Все файлы'],['КТ/Рентген'],['Фото'],['3D модели'],['Документы']],state.fileTab,'file-tab')}<div class="file-grid">${files.filter(f=>state.fileTab==='Все файлы'||f[3]===state.fileTab).map(([src,name,date])=>`<button class="file-card" data-action="file-preview" data-value="${name}"><img src="${assets+src}" alt=""><strong>${name}</strong><small>${date}</small></button>`).join('')}</div><input type="file" id="page-upload" multiple hidden>`)}
function messagesPage(){const contacts=[['Техподдержка','Ваш заказ CD-1039 передан в работу.','Вчера','Т'],['Алексей Петров','Добрый день! Можно уточнить срок...','10:24','АП'],['Мария Соколова','Файлы успешно загружены.','10:03','МС'],['Служба качества','Спасибо за обращение! Мы проверим...','09:03','С']];shell(`${title('Сообщения')}<div class="messages-layout"><div class="contacts"><label class="search">${icon('search',16)}<input placeholder="Поиск сообщений..."></label>${contacts.map((c,i)=>`<button class="contact ${i===1?'active':''}" data-action="contact"><span class="contact-avatar">${c[3]}</span><span><strong>${c[0]}</strong><small>${c[1]}</small></span><time>${c[2]}</time></button>`).join('')}</div><div class="conversation"><div class="conversation-head"><span class="contact-avatar photo">АП</span><span><strong>Алексей Петров</strong><small><i class="online"></i> Активен</small></span><button class="more-btn">···</button></div><div class="chat-bubbles">${state.messages.map(m=>`<div class="bubble ${m.from}"><p>${escapeHtml(m.text)}</p><time>${m.time}</time></div>`).join('')}</div><form id="chat-form" class="chat-compose"><input id="chat-input" placeholder="Напишите сообщение..." value="${escapeHtml(state.chatText)}" autocomplete="off"><button type="button" class="attach-btn" data-action="attach" aria-label="Прикрепить файл">${icon('paperclip',19)}</button><button class="send-btn" aria-label="Отправить">➤</button></form></div></div>`)}
function clinicPage(){shell(`${title('Моя клиника')}${tabs([['Основная информация'],['Контактные лица'],['Настройки'],['Безопасность']],state.clinicTab,'clinic-tab')}<div class="clinic-content"><div class="clinic-photo"><img src="${assets}clinic.png" alt="Здание клиники"><button data-action="change-logo">Изменить логотип</button></div><div class="clinic-form"><div class="form-grid">${field('Название клиники',textInput('Dental Clinic'))}${field('ИНН',textInput('7701234567'))}${field('Адрес',textInput('г. Москва, ул. Примерная, д. 1'))}${field('Телефон',textInput('+7 (000) 123-45-67'))}${field('Email',textInput('info@dentalclinic.ru'))}<div class="save-field">${button('Сохранить изменения','save-clinic')}</div></div></div></div>`)}
function referencePage(){shell(`${title('Справочник','Информация о конструкциях, материалах и оформлении заказов.')}<div class="reference-grid">${[['Коронки E.max','Эстетичные цельнокерамические реставрации.'],['Виниры','Тонкие накладки для восстановления улыбки.'],['Мостовидные протезы','Конструкции для замещения отсутствующих зубов.'],['3D сканирование','Цифровые слепки для точной работы.']].map(([h,p])=>`<article class="reference-card">${icon('book',25)}<h3>${h}</h3><p>${p}</p></article>`).join('')}</div>`)}
function render(){const page=state.page;({home:dashboard,new:newOrder,orders:ordersPage,detail,files:filesPage,messages:messagesPage,clinic:clinicPage,reference:referencePage}[page]||dashboard)()}
function notify(message){state.toast=message;render();clearTimeout(notify.timer);notify.timer=setTimeout(()=>{state.toast='';$('.toast')?.classList.remove('visible')},3000)}
document.addEventListener('click',event=>{const el=event.target.closest('[data-page],[data-order],[data-tooth],[data-step],[data-action]');if(!el)return;if(el.dataset.page){state.page=el.dataset.page;if(state.page==='new')state.step=0;render();return}if(el.dataset.order){state.orderId=el.dataset.order;state.page='detail';render();return}if(el.dataset.tooth){const n=Number(el.dataset.tooth);state.selectedTeeth=state.selectedTeeth.includes(n)?state.selectedTeeth.filter(x=>x!==n):[...state.selectedTeeth,n].sort((a,b)=>a-b);render();return}if(el.dataset.step!==undefined){state.step=Number(el.dataset.step);render();return}const a=el.dataset.action,v=el.dataset.value;if(a==='new'){state.page='new';state.step=0}else if(a==='next'){if(state.step<4)state.step++;else{const id=`CD-${1043+orders.filter(o=>Number(o.id.slice(3))>=1043).length}`;orders.unshift({id,patient:`${state.form.surname} ${state.form.initials}`,work:state.form.construction,date:state.form.due.split('-').reverse().join('.'),status:'Новый',sum:'—',image:'tooth.png'});state.page='detail';state.orderId=id;notify('Заказ создан локально');return}}else if(a==='previous')state.step--;else if(a==='filter')state.filter=v;else if(a==='file-tab')state.fileTab=v;else if(a==='detail-tab')state.detailTab=v;else if(a==='clinic-tab')state.clinicTab=v;else if(a==='dentition')state.dentition=v;else if(a==='work')state.work=v;else if(a==='clear-teeth')state.selectedTeeth=[];else if(a==='open-messages')state.page='messages';else if(a==='upload'){$('#page-upload')?.click();return}else if(a==='remove-file'){state.uploaded=state.uploaded.filter(n=>n!==v)}else if(a==='menu'){$('#sidebar').classList.toggle('open');return}else if(a==='save-clinic'){notify('Изменения сохранены локально');return}else if(a==='file-preview'){notify(v);return}else if(a==='notifications'){notify('Новых уведомлений нет');return}else if(a==='filters'){notify('Используйте вкладки для фильтрации заказов');return}else if(a==='more'){notify('Дополнительные действия появятся после подключения сервера');return}else if(a==='change-logo'){notify('Загрузка логотипа появится после подключения сервера');return}else if(a==='attach'){notify('Прикрепление файлов доступно в разделе «Файлы»');return}else if(a==='contact'){notify('Демонстрационный диалог');return}else return;render()});
document.addEventListener('input',event=>{if(event.target.dataset.field)state.form[event.target.dataset.field]=event.target.value;if(event.target.id==='order-search'){state.query=event.target.value;const table=$('.table-wrap');if(table)table.outerHTML=orderTable(filteredOrders());}if(event.target.id==='chat-input')state.chatText=event.target.value});
document.addEventListener('change',event=>{if(event.target.dataset.field)state.form[event.target.dataset.field]=event.target.value;if(event.target.type==='file'){state.uploaded.push(...Array.from(event.target.files).map(f=>f.name));notify(`${event.target.files.length} файл(ов) добавлено локально`)}});
document.addEventListener('submit',event=>{if(event.target.id==='chat-form'){event.preventDefault();const msg=state.chatText.trim();if(msg){state.messages.push({from:'me',text:msg,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});state.chatText='';render()}}});
render();
